Pronia/Areas/ProniaAdmin/ViewModels/Slide/CreateSlideVM.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Pronia.Areas.ProniaAdmin.ViewModels
{
	public class CreateSlideVm
	{
		[Required(ErrorMessage = "Title is required")]
		[MaxLength(25, ErrorMessage = "Max length is 25")]
		public string Title { get; set; }
		public string Subtitle { get; set; }
		public string Description { get; set; }
		public int Order { get; set; }
		public IFormFile? Photo { get; set; }
	}
}

Pronia/Areas/ProniaAdmin/ViewModels/Slide/UpdateSlideVM.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Pronia.Areas.ProniaAdmin.ViewModels
{
	public class UpdateSlideVM
	{
		[Required(ErrorMessage = "Title is required")]
		[MaxLength(25, ErrorMessage = "Max length is 25")]
		public string Title { get; set; }
		public string Subtitle { get; set; }
		public string Description { get; set; }
		public string ImageUrl { get; set; }
		public int Order { get; set; }
		public IFormFile? Photo { get; set; }
	}
}

Pronia/Models/Slide.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Pronia.Models;

public class Slide
{
    public int Id { get; set; }
    [Required(ErrorMessage ="Title is required")]
    [MaxLength(25, ErrorMessage = "Max length is 25")]
    public string Title { get; set; }
    public string Subtitle { get; set; }
    public string Description { get; set; }
    public string? ImageUrl { get; set; }
    public int Order { get; set; }
    [NotMapped]
    public IFormFile? Photo { get; set; }
}

Pronia/Areas/ProniaAdmin/Controllers/SlideController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pronia.Areas.ProniaAdmin.ViewModels;
using Pronia.DAL;
using Pronia.Models;
using Pronia.Utilities.Extentions;
using System.Data;

namespace Pronia.Areas.ProniaAdmin.Controllers
{
	[Area("ProniaAdmin")]
	public class SlideController : Controller
	{
		private readonly AppDbContext _context;
		private readonly IWebHostEnvironment _env;

		public SlideController(AppDbContext context, IWebHostEnvironment env)
		{
			_context = context;
			_env = env;
		}
		[Authorize(Roles = "Admin,Moderator")]
		public async Task<IActionResult> Index()
		{
			var slides = await _context.Slides.ToListAsync();
			return View(slides);
		}
		[Authorize(Roles = "Admin,Moderator")]
		public IActionResult Create()
		{
			return View();
		}
		[HttpPost]
		public async Task<IActionResult> Create(CreateSlideVm slideVM)
		{
			if(!ModelState.IsValid) return View();
			if (!slideVM.Photo.ValidateType())
			{
				ModelState.AddModelError("Photo", "Wrong file type");
				return View();
			}
			if (slideVM.Photo.ValidateSize(2 * 1024))
			{
				ModelState.AddModelError("Photo", "It shouldn't exceed 2 mb");
				return View();
			}


			string fileName = await slideVM.Photo.CreateFile(_env.WebRootPath, "assets", "images", "website-images");

			Slide slide = new Slide()
			{
				ImageUrl = fileName,
				Description = slideVM.Description,
				Order = slideVM.Order,
				Title = slideVM.Title,
				Subtitle = slideVM.Subtitle
			};

			await _context.Slides.AddAsync(slide);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}
		[Authorize(Roles = "Admin,Moderator")]
		public async Task<IActionResult> Details(int id)
		{
			if (id <= 0) return BadRequest();
			var slide = await _context.Slides.FirstOrDefaultAsync(s => s.Id == id);
			if (slide == null) return NotFound();

			return View(slide);
		}
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Delete(int id)
		{
			if (id <= 0) return BadRequest();
			Slide slide = await _context.Slides.FirstOrDefaultAsync(s => s.Id == id);
			if (slide == null) return NotFound();

			slide.ImageUrl.DeleteFile(_env.WebRootPath, "assets", "images", "website-images");
			_context.Slides.Remove(slide);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}
		[Authorize(Roles = "Admin,Moderator")]
		public async Task<IActionResult> Update(int id)
		{
			if (id <= 0) return BadRequest();
			Slide slide = await _context.Slides.FirstOrDefaultAsync(c => c.Id == id);
			if (slide is null) return NotFound();

			UpdateSlideVM vm = new UpdateSlideVM()
			{
				Subtitle = slide.Subtitle,
				Title = slide.Title,
				Description = slide.Description,
				ImageUrl = slide.ImageUrl,
				Order = slide.Order
			};
			return View(vm);
		}

		[HttpPost]
		public async Task<IActionResult> Update(int id, UpdateSlideVM slidevm)
		{
			if (!ModelState.IsValid) return View(slidevm);
			Slide existed = await _context.Slides.FirstOrDefaultAsync(c => c.Id == id);
			if (existed is null) return NotFound();

			bool result = _context.Slides.Any(c => c.Title == slidevm.Title && c.Order == slidevm.Order && c.Id != id);
			if (!result)
			{
				if (slidevm.Photo is not null)
				{
					if (!slidevm.Photo.ValidateType())
					{
						ModelState.AddModelError("Photo", "Wrong file type");
						return View(slidevm);
					}
					if (slidevm.Photo.ValidateSize(2 * 1024))
					{
						ModelState.AddModelError("Photo", "It shouldn't exceed 2 mb");
						return View(slidevm);
					}
					string newImage = await slidevm.Photo.CreateFile(_env.WebRootPath, "assets", "images", "website-images");
					existed.ImageUrl.DeleteFile(_env.WebRootPath, "assets", "images", "website-images");
					existed.ImageUrl = newImage;

				}

				existed.Title = slidevm.Title;
				existed.Description = slidevm.Description;
				existed.Subtitle = slidevm.Subtitle;
				existed.Order = slidevm.Order;
				await _context.SaveChangesAsync();
			}
			else
			{
				ModelState.AddModelError("Title", "There is already such title");
				ModelState.AddModelError("Order", "There is already such order");
				return View(existed);
			}

			
			return RedirectToAction(nameof(Index));
		}
	}
}

Pronia/Controllers/DetailController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pronia.DAL;
using Pronia.Models;
using Pronia.Utilities.Exceptions;
using Pronia.ViewModels;

namespace Pronia.Controllers
{
    public class DetailController : Controller
    {
        //public IActionResult Index()
        //{
        //    return View();
        //}
        private readonly AppDbContext _context;

        public DetailController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Detail(int id)
        {
            if (id <= 0) throw new WrongRequestException("Your request is wrong");
            Product product = await _context.Products
                .Include(p=>p.ProductColors).ThenInclude(pc=>pc.Color)
                .Include(p=>p.ProductSizes).ThenInclude(ps=>ps.Size)
                .Include(p=>p.ProductImages)
                .Include(p=>p.ProductTags).ThenInclude(pt=>pt.Tag)
                .Include(p=>p.Category).FirstOrDefaultAsync(p => p.Id == id);

            if (product is null) throw new NotFoundException("There is no such product");
            List<Product> RelatedProducts = await _context.Products.Include(p=>p.ProductImages).Where(p => p.CategoryId == product.CategoryId && p.Id!=product.Id).ToListAsync();
            Console.WriteLine(RelatedProducts.Count);

            DetailVM vm = new DetailVM()
            {
                Product = product,
                RelatedProducts = RelatedProducts
            };
            if (product == null) return NotFound();



            return View(vm);
        }
    }
}

Pronia/Areas/ProniaAdmin/Views/Slide/Create.cshtml
@model CreateSlideVm
<div class="content-wrapper">
	<div class="row">
		<div class="col-lg-12 grid-margin stretch-card">
			<div class="card">
				<div class="card-body">
					<form class="forms-sample" method="post" enctype="multipart/form-data">
						<div class="form-group">
							<label asp-for="Photo">Photo</label>
							<input asp-for="Photo" class="form-control" id="Photo" placeholder="Photo" >
							<span class="text-danger" asp-validation-for="Photo" ></span>
						</div>
						<div class="form-group">
							<label asp-for="Title">Title</label>
							<input asp-for="Title"  class="form-control" id="Title" placeholder="Title">
							<span class="text-danger" asp-validation-for="Title"></span>
						</div>
						<div class="form-group">
							<label asp-for="Subtitle">Subtitle</label>
							<input asp-for="Subtitle"  class="form-control" id="Subtitle" placeholder="Subtitle">
							<span class="text-danger" asp-validation-for="Subtitle"></span>
						</div>
						<div class="form-group">
							<label asp-for="Order">Order</label>
							<input asp-for="Order" class="form-control" id="Order" placeholder="Order" >
							<span class="text-danger" asp-validation-for="Order"></span>
						</div>
						<div class="form-group">
							<label asp-for="Description">Description</label>
							<input asp-for="Description" class="form-control" id="name" placeholder="Description" >
							<span class="text-danger" asp-validation-for="Description"></span>
						</div>

						<button type="submit" class="btn btn-primary me-2">Submit</button>
						<a asp-action="Index" class="btn btn-light">Cancel</a>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

Pronia/Areas/ProniaAdmin/Views/Slide/Details.cshtml
@model Slide
<div class="d-flex flex-row">
	<div>
		<img src="~/assets/images/website-images//@Model.ImageUrl" class="card-img" class="card-img-top" alt="...">
	</div>

	<div class="m-5">
		<h1 >@Model.Title</h1>
		<h3 >@Model.Subtitle</h3>
		<p >@Model.Description</p>
	</div>
</div>

Pronia/Areas/ProniaAdmin/Views/Slide/Index.cshtml
@model List<Slide>
@{
    int count = 0;
}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Slides</h4>
                    <a class="btn btn-success btn-info" asp-controller="Slide" asp-action="Create">Create Slide</a>
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        No
                                    </th>
                                    <th>
                                        Image
                                    </th>
                                    <th>
                                        Title
                                    </th>
                                    <th>
                                        Order
                                    </th>
                                    <th>
                                        Settings
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (Slide slide in Model)
                                {
                                    count++;
                                    <tr>
                                        <td>
                                            @count
                                        </td>
                                        <td>
                                            <img style="width:150px; height:150px;" src="~/assets/images/website-images//@slide.ImageUrl" />
                                        </td>
                                        <td>
                                           @slide.Title
                                        </td>
                                        <td>
                                            @slide.Order
                                        </td>
                                        <td>
                                            <a asp-action="Update" asp-route-id="@slide.Id" class="btn btn-warning btn-info"> <i class="mdi mdi-pencil"></i> Update</a>
                                            <a asp-action="Delete" asp-route-id="@slide.Id" class="btn btn-danger btn-info"> <i class="mdi mdi-delete"></i> Delete</a>
                                            <a asp-action="Details" asp-route-id="@slide.Id" class="btn btn-primary btn-info"> <i class="mdi mdi-open-in-new"></i> Details</a>
                                        </td>
                                    </tr>


                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Pronia/Areas/ProniaAdmin/Views/Slide/Update.cshtml
@model UpdateSlideVM
<div class="content-wrapper">
	<div class="row">
		<div class="col-lg-12 grid-margin stretch-card">
			<div class="card">
				<div class="card-body">
					<form class="forms-sample" method="post" enctype="multipart/form-data">
						<div class="form-group">
							<img src="~/assets/images/website-images/@Model.ImageUrl" width="120px" />
							<input asp-for="ImageUrl" type="hidden" class="form-control">
						</div>
						<div class="form-group">
							<label asp-for="Photo">Choose new photo</label>
							<input asp-for="Photo" class="form-control" id="Photo" placeholder="Photo">
							<span class="text-danger" asp-validation-for="Photo"></span>
						</div>
						<div class="form-group">
							<label asp-for="Title">Title</label>
							<input asp-for="Title" class="form-control" id="Title" placeholder="Title">
							<span class="text-danger" asp-validation-for="Title"></span>
						</div>
						<div class="form-group">
							<label asp-for="Subtitle">Subtitle</label>
							<input asp-for="Subtitle" class="form-control" id="Subtitle" placeholder="Subtitle">
							<span class="text-danger" asp-validation-for="Subtitle"></span>
						</div>
						<div class="form-group">
							<label asp-for="Order">Order</label>
							<input asp-for="Order" class="form-control" id="Order" placeholder="Order">
							<span class="text-danger" asp-validation-for="Order"></span>
						</div>
						<div class="form-group">
							<label asp-for="Description">Description</label>
							<input asp-for="Description" class="form-control" id="name" placeholder="Description">
							<span class="text-danger" asp-validation-for="Description"></span>
						</div>

						<button type="submit" class="btn btn-primary me-2">Submit</button>
						<a asp-action="Index" class="btn btn-light">Cancel</a>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>