Pronia/Areas/ProniaAdmin/ViewModels/Tag/CreateTagVM.cs
using System.ComponentModel.DataAnnotations;

namespace Pronia.Areas.ProniaAdmin.ViewModels
{
	public class CreateTagVM
	{
		[Required(ErrorMessage = "Name is required")]
		[MaxLength(25, ErrorMessage = "Name's max length is 25")]
		public string Name { get; set; }
	}
}

Pronia/Areas/ProniaAdmin/ViewModels/Tag/UpdateTagVM.cs
using System.ComponentModel.DataAnnotations;

namespace Pronia.Areas.ProniaAdmin.ViewModels
{
	public class UpdateTagVM
	{
		[Required(ErrorMessage = "Name is required")]
		[MaxLength(25, ErrorMessage = "Name's max length is 25")]
		public string Name { get; set; }
	}
}

Pronia/Models/Tag.cs
using System.ComponentModel.DataAnnotations;

namespace Pronia.Models
{
    public class Tag
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required")]
        [MaxLength(25, ErrorMessage = "Name's max length is 25")]
        public string Name { get; set; }
        public List<ProductTag>? ProductTags { get; set; }
    }
}

Pronia/Areas/ProniaAdmin/Controllers/TagController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pronia.Areas.ProniaAdmin.ViewModels;
using Pronia.DAL;
using Pronia.Models;
using System.Data;

namespace Pronia.Areas.ProniaAdmin.Controllers
{
    [Area("ProniaAdmin")]
    public class TagController : Controller
    {
        private readonly AppDbContext _context;

        public TagController(AppDbContext context)
        {
            _context = context;
        }
		[Authorize(Roles = "Admin,Moderator")]
		public async Task<IActionResult> Index(int page)
        {
            double count = await _context.Tags.CountAsync();
            var Tags = await _context.Tags.Skip(page*2).Take(2)
                .Include(t=>t.ProductTags).ToListAsync();
            PaginationVM<Tag> pagination = new PaginationVM<Tag>()
            {
                CurrentPage = page,
                TotalPage = Math.Ceiling(count / 2),
                Items = Tags
            };
            return View(pagination);
        }
		[Authorize(Roles = "Admin,Moderator")]
		public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateTagVM tagVM)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            bool result = _context.Tags.Any(c => c.Name.ToLower().Trim() == tagVM.Name.ToLower().Trim());
            if (result)
            {
                ModelState.AddModelError("Name", "This tag already exists");
                return View();
            }
            var tag = new Tag
            {
                Name = tagVM.Name,
            };
            await _context.Tags.AddAsync(tag);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
		[Authorize(Roles = "Admin,Moderator")]
		public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) return BadRequest();
            Tag tag = await _context.Tags.FirstOrDefaultAsync(c => c.Id == id);
            if (tag is null) return NotFound();
            var vm = new UpdateTagVM { 
                Name = tag.Name,
            };

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateTagVM tagVM)
        {
            if (!ModelState.IsValid) return View();

            Tag existed = await _context.Tags.FirstOrDefaultAsync(c => c.Id == id);
            if (existed is null) return NotFound();
            bool result = _context.Tags.Any(c => c.Name == tagVM.Name && c.Id != id);
            if (result)
            {
                ModelState.AddModelError("Name", "There is already such tag");
                return View();
            }

            existed.Name = tagVM.Name;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) return BadRequest();
            var existed = await _context.Tags.FirstOrDefaultAsync(c => c.Id == id);
            if (existed is null) return NotFound();
            _context.Tags.Remove(existed);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
		[Authorize(Roles = "Admin,Moderator")]
		public async Task<IActionResult> Details(int id)
		{
			if (id <= 0) return BadRequest();
			var tag = await _context.Tags.Include(c => c.ProductTags).
                ThenInclude(p => p.Product).
                ThenInclude(p=>p.ProductImages).
                FirstOrDefaultAsync(s => s.Id == id);
			if (tag == null) return NotFound();

			return View(tag);
		}
	}
}

Pronia/Controllers/DetailController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pronia.DAL;
using Pronia.Models;
using Pronia.Utilities.Exceptions;
using Pronia.ViewModels;

namespace Pronia.Controllers
{
    public class DetailController : Controller
    {
        //public IActionResult Index()
        //{
        //    return View();
        //}
        private readonly AppDbContext _context;

        public DetailController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Detail(int id)
        {
            if (id <= 0) throw new WrongRequestException("Your request is wrong");
            Product product = await _context.Products
                .Include(p=>p.ProductColors).ThenInclude(pc=>pc.Color)
                .Include(p=>p.ProductSizes).ThenInclude(ps=>ps.Size)
                .Include(p=>p.ProductImages)
                .Include(p=>p.ProductTags).ThenInclude(pt=>pt.Tag)
                .Include(p=>p.Category).FirstOrDefaultAsync(p => p.Id == id);

            if (product is null) throw new NotFoundException("There is no such product");
            List<Product> RelatedProducts = await _context.Products.Include(p=>p.ProductImages).Where(p => p.CategoryId == product.CategoryId && p.Id!=product.Id).ToListAsync();
            Console.WriteLine(RelatedProducts.Count);

            DetailVM vm = new DetailVM()
            {
                Product = product,
                RelatedProducts = RelatedProducts
            };
            if (product == null) return NotFound();



            return View(vm);
        }
    }
}

Pronia/Areas/ProniaAdmin/Views/Tag/Create.cshtml
@model CreateTagVM
<div class="content-wrapper">
	<div class="row">
		<div class="col-lg-12 grid-margin stretch-card">
			<div class="card">
				<div class="card-body">
					<form class="forms-sample" method="post">
						<div class="form-group">
							<label for="name">Name</label>
							<input asp-for="@Model.Name" type="text" class="form-control" id="name" placeholder="Name" name="name">
							<span class="text-danger" asp-validation-for="Name"></span>
						</div>

						<button type="submit" class="btn btn-primary me-2">Submit</button>
						<a asp-action="Index" class="btn btn-light">Cancel</a>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

Pronia/Areas/ProniaAdmin/Views/Tag/Details.cshtml
@model Tag
<div class="container">
	<h1 class="m-5">@Model.Name</h1>
	<div class="d-flex flex-wrap">
		@foreach (ProductTag pTag in Model.ProductTags)
		{
			<div class="card m-1" style="width: 18rem;">
				<img src="~/assets/images/website-images/@pTag.Product.ProductImages.FirstOrDefault(p=>p.IsPrimary==true).Url" class="card-img-top" alt="...">
				<div class="card-body">
					<h5 class="card-title">@pTag.Product.Name</h5>
					<p class="card-text">@pTag.Product.Description</p>
				</div>
			</div>
		}
	</div>
</div>

Pronia/Areas/ProniaAdmin/Views/Tag/Index.cshtml
@model PaginationVM<Tag>
@{
    int count = Model.CurrentPage*2;
}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Tags</h4>
                    <a class="btn btn-success btn-info" asp-controller="Tag" asp-action="Create">Create Tag</a>
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        No
                                    </th>
                                    <th>
                                        Name
                                    </th>
                                    <th>
                                        Products Count
                                    </th>
                                    <th>
                                        Settings
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (Tag tag in Model.Items)
                                {
                                    count++;
                                    <tr>
                                        <td>
                                            @count
                                        </td>
                                        <td>
                                            @tag.Name
                                        </td>
                                        <td>
                                            @tag.ProductTags.Count
                                        </td>
                                        <td>
                                            <a asp-action="Update" asp-route-id="@tag.Id" class="btn btn-warning btn-info"> <i class="mdi mdi-pencil"></i> Update</a>
                                            <a asp-action="Delete" asp-route-id="@tag.Id" class="btn btn-danger btn-info"> <i class="mdi mdi-delete"></i> Delete</a>
                                            <a asp-action="Details" asp-route-id="@tag.Id" class="btn btn-primary btn-info"> <i class="mdi mdi-open-in-new"></i> Details</a>
                                        </td>
                                    </tr>


                                }

                            </tbody>
                        </table>
                    </div>
                    <nav aria-label="Page navigation example">
                        <ul class="pagination">
                            <li class="page-item @(Model.CurrentPage==0?"disabled":"")"><a class="page-link" asp-route-page="@(Model.CurrentPage-1)" asp-action="Index" asp-controller="Tag">Previous</a></li>
                            @for (int i = 0; i < Model.TotalPage; i++)
                            {
                                <li class="page-item @(i==Model.CurrentPage?"disabled":"")"><a class="page-link" asp-route-page="@(i)" asp-action="Index" asp-controller="Tag">@(i + 1)</a></li>
                            }
                            <li class="page-item @(Model.CurrentPage==Model.TotalPage-1?"disabled":"")"><a class="page-link" asp-route-page="@(Model.CurrentPage+1)" asp-action="Index" asp-controller="Tag">Next</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

Pronia/Areas/ProniaAdmin/Views/Tag/Update.cshtml
@model UpdateTagVM
<div class="content-wrapper">
	<div class="row">
		<div class="col-lg-12 grid-margin stretch-card">
			<div class="card">
				<div class="card-body">
					<form class="forms-sample" method="post">
						<div class="form-group">
							<label for="name">Name</label>
							<input asp-for="@Model.Name" type="text" class="form-control" id="name" placeholder="Name">
							<span class="text-danger" asp-validation-for="Name"></span>
						</div>

						<button type="submit" class="btn btn-primary me-2">Submit</button>
						<a asp-action="Index" class="btn btn-light">Cancel</a>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>