Pronia/Areas/ProniaAdmin/ViewModels/Color/CreateColorVM.cs
using System.ComponentModel.DataAnnotations;

namespace Pronia.Areas.ProniaAdmin.ViewModels
{
	public class CreateColorVM
	{
		[Required(ErrorMessage = "Name is required")]
		[MaxLength(25, ErrorMessage = "Name's max length is 25")]
		public string Name { get; set; }
	}
}

Pronia/Areas/ProniaAdmin/ViewModels/Color/UpdateColorVM.cs
using System.ComponentModel.DataAnnotations;

namespace Pronia.Areas.ProniaAdmin.ViewModels
{
	public class UpdateColorVM
	{
		[Required(ErrorMessage = "Name is required")]
		[MaxLength(25, ErrorMessage = "Name's max length is 25")]
		public string Name { get; set; }
	}
}

Pronia/Models/Color.cs
using System.ComponentModel.DataAnnotations;

namespace Pronia.Models
{
    public class Color
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Name is required")]
        [MaxLength(25, ErrorMessage = "Name's max length is 25")]
        public string Name { get; set; }
        public List<ProductColor>? ProductColors { get; set; }
    }
}

Pronia/Areas/ProniaAdmin/Controllers/ColorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pronia.Areas.ProniaAdmin.ViewModels;
using Pronia.DAL;
using Pronia.Models;
using System.Data;

namespace Pronia.Areas.ProniaAdmin.Controllers
{
	[Area("ProniaAdmin")]
	public class ColorController : Controller
	{
		private readonly AppDbContext _context;

		public ColorController(AppDbContext context)
        {
			_context = context;
		}
		[Authorize(Roles = "Admin,Moderator")]
		public async Task<IActionResult> Index()
		{
			var colors = await _context.Colors.Include(c=>c.ProductColors).ToListAsync();
			return View(colors);
		}
		[Authorize(Roles = "Admin,Moderator")]
		public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateColorVM colorVM)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            bool result = _context.Colors.Any(c => c.Name.ToLower().Trim() == colorVM.Name.ToLower().Trim());
            if (result)
            {
                ModelState.AddModelError("Name", "This color already exists");
                return View();
            }
            var color = new Color
            {
                Name = colorVM.Name
            };
            await _context.Colors.AddAsync(color);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
		[Authorize(Roles = "Admin,Moderator")]
		public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) return BadRequest();
            Color color = await _context.Colors.FirstOrDefaultAsync(c => c.Id == id);
            if (color is null) return NotFound();
            var vm = new UpdateColorVM
            {
                Name = color.Name
            };
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateColorVM colorVM)
        {
            if (!ModelState.IsValid) return View();

            Color existed = await _context.Colors.FirstOrDefaultAsync(c => c.Id == id);
            if (existed is null) return NotFound();
            bool result = _context.Colors.Any(c => c.Name == colorVM.Name && c.Id != id);
            if (result)
            {
                ModelState.AddModelError("Name", "There is already such color");
                return View();
            }

            existed.Name = colorVM.Name;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) return BadRequest();
            var existed = await _context.Colors.FirstOrDefaultAsync(c => c.Id == id);
            if (existed is null) return NotFound();
            _context.Colors.Remove(existed);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
		[Authorize(Roles = "Admin,Moderator")]
		public async Task<IActionResult> Details(int id)
        {
            if (id <= 0) return BadRequest();
            var color = await _context.Colors
                .Include(c => c.ProductColors)
                .ThenInclude(pc => pc.Product)
                .ThenInclude(p => p.ProductImages).
                FirstOrDefaultAsync(s => s.Id == id);
            if (color == null) return NotFound();

            return View(color);
        }
    }
}

Pronia/Controllers/DetailController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pronia.DAL;
using Pronia.Models;
using Pronia.Utilities.Exceptions;
using Pronia.ViewModels;

namespace Pronia.Controllers
{
    public class DetailController : Controller
    {
        //public IActionResult Index()
        //{
        //    return View();
        //}
        private readonly AppDbContext _context;

        public DetailController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Detail(int id)
        {
            if (id <= 0) throw new WrongRequestException("Your request is wrong");
            Product product = await _context.Products
                .Include(p=>p.ProductColors).ThenInclude(pc=>pc.Color)
                .Include(p=>p.ProductSizes).ThenInclude(ps=>ps.Size)
                .Include(p=>p.ProductImages)
                .Include(p=>p.ProductTags).ThenInclude(pt=>pt.Tag)
                .Include(p=>p.Category).FirstOrDefaultAsync(p => p.Id == id);

            if (product is null) throw new NotFoundException("There is no such product");
            List<Product> RelatedProducts = await _context.Products.Include(p=>p.ProductImages).Where(p => p.CategoryId == product.CategoryId && p.Id!=product.Id).ToListAsync();
            Console.WriteLine(RelatedProducts.Count);

            DetailVM vm = new DetailVM()
            {
                Product = product,
                RelatedProducts = RelatedProducts
            };
            if (product == null) return NotFound();



            return View(vm);
        }
    }
}

Pronia/Areas/ProniaAdmin/Views/Color/Create.cshtml
@model CreateColorVM
<div class="content-wrapper">
	<div class="row">
		<div class="col-lg-12 grid-margin stretch-card">
			<div class="card">
				<div class="card-body">
					<form class="forms-sample" method="post">
						<div class="form-group">
							<label for="name">Name</label>
							<input asp-for="@Model.Name" type="text" class="form-control" placeholder="Name">
							<span class="text-danger" asp-validation-for="Name"></span>
						</div>

						<button type="submit" class="btn btn-primary me-2">Submit</button>
						<a asp-action="Index" class="btn btn-light">Cancel</a>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

Pronia/Areas/ProniaAdmin/Views/Color/Details.cshtml
@model Color
<div class="container">
	<h1 class="m-5">@Model.Name</h1>
	<div class="d-flex flex-wrap">
		@foreach (ProductColor pColor in Model.ProductColors)
		{
			<div class="card m-1" style="width: 18rem;">
				<img src="~/assets/images/website-images/@pColor.Product.ProductImages.FirstOrDefault(p=>p.IsPrimary==true).Url" class="card-img-top" alt="...">
				<div class="card-body">
					<h5 class="card-title">@pColor.Product.Name</h5>
					<p class="card-text">@pColor.Product.Description</p>
				</div>
			</div>
		}
	</div>
</div>

Pronia/Areas/ProniaAdmin/Views/Color/Index.cshtml
@model List<Color>
@{
    int count = 0;
}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Colors</h4>
                    <a class="btn btn-success btn-info" asp-controller="Color" asp-action="Create">Create Color</a>
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        No
                                    </th>
                                    <th>
                                        Name
                                    </th>
                                    <th>
                                        Products Count
                                    </th>
                                    <th>
                                        Settings
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (Color color in Model)
                                {
                                    count++;
                                    <tr>
                                        <td>
                                            @count
                                        </td>
                                        <td>
                                            @color.Name
                                        </td>
                                        <td>
                                            @color.ProductColors.Count
                                        </td>
                                        <td>
                                            <a asp-action="Update" asp-route-id="@color.Id" class="btn btn-warning btn-info"> <i class="mdi mdi-pencil"></i> Update</a>
                                            <a asp-action="Delete" asp-route-id="@color.Id" class="btn btn-danger btn-info"> <i class="mdi mdi-delete"></i> Delete</a>
                                            <a asp-action="Details" asp-route-id="@color.Id" class="btn btn-primary btn-info"> <i class="mdi mdi-open-in-new"></i> Details</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Pronia/Areas/ProniaAdmin/Views/Color/Update.cshtml
@model UpdateColorVM
<div class="content-wrapper">
	<div class="row">
		<div class="col-lg-12 grid-margin stretch-card">
			<div class="card">
				<div class="card-body">
					<form class="forms-sample" method="post">
						<div class="form-group">
							<label for="name">Name</label>
							<input asp-for="@Model.Name" type="text" class="form-control" placeholder="Name">
							<span class="text-danger" asp-validation-for="Name"></span>
						</div>

						<button type="submit" class="btn btn-primary me-2">Submit</button>
						<a asp-action="Index" class="btn btn-light">Cancel</a>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>